//! Swift lane expected-failure tables (moved verbatim under per-lane ownership; no rows re-authored).
//!
//! Swift-lane expected-outcome surface (per-lane-e2e-validation EL-4). The
//! lane harness module consumes only this table via
//! `super::expectations::swift::…`; no other lane may absorb these rows.

/// Exempla that are expected to fail Swift emission (codegen not implemented
/// for these expression/statement shapes yet).
///
/// SC-002+ops/scribe: 54 exempla pass. The remaining exempla use features
/// deferred to SC-003 (collections), SC-004 (classes/structs), SC-005 (enums),
/// SC-006 (failable), SC-007 (optionals), SC-008 (stdlib), or are
/// intentionally rejected by Faber semantic analysis.
pub(crate) const SWIFT_EXPECTED_FAILURES: &[&str] = &[
    // Y: quarantined 2026-08-06; full Radix e2e found broader Swift backend
    // compile/runtime/output debt than the prior ledger covered.
    "ad/async-solum-leget.fab",
    "ad/async-tempus-dormiet.fab",
    "ad/sermo-conversio.fab",
    "ad/sermo-live-directional.fab",
    "ad/sermo-recovery.fab",
    "ad/sermo-tuus.fab",
    "ad/sermo-vacuum.fab",
    "ad/solum-lege-generic.fab",
    "annotation-sugar/cli-braced.fab",
    "annotation-sugar/optio-braced.fab",
    "argumenta/argumenta.fab",
    "assertio/nonnulla.fab",
    "cede/cede.fab",
    "clausa/clausa.fab",
    "clausura/clausura.fab",
    "cli/cli.fab",
    "conversio/collectiones.fab",
    "conversio/fallibilis.fab",
    "conversio/instans-valor-carrier.fab",
    "conversio/instans.fab",
    "conversio/lista-tensor-shaped.fab",
    "conversio/regex.fab",
    "conversio/rectangular-lista-literal-tensor.fab",
    "conversio/tensor.fab",
    "conversio/valor-genus.fab",
    "conversio/valor-boxing.fab",
    "conversio/valor-scalaria.fab",
    "conversio/valor-tensor.fab",
    "conversio/verte-aggregate.fab",
    "cuda/addita-proof.fab",
    "cuda/matmul-proof.fab",
    "cuda/summa-proof.fab",
    "cura/cura.fab",
    "cura/nidificatus.fab",
    "curata/curata.fab",
    "cursor/cursor.fab",
    "de/de.fab",
    "descriptio/descriptio.fab",
    "destructura/literal.fab",
    "destructura/objectum.fab",
    "discerne/discerne.fab",
    "errata/errata.fab",
    "est/est.fab",
    "exitus/exitus.fab",
    "fac/fac-cape.fab",
    "fient/fient.fab",
    "fiet/fiet.fab",
    "figendum/figendum.fab",
    "fiunt/fiunt.fab",
    "functio/generic-call-type-args.fab",
    "functio/in-ex.fab",
    "functio/sponte-vel.fab",
    "futura/futura.fab",
    "generic/generic.fab",
    "generic/genus.fab",
    "genus/methodi.fab",
    "gpu-core-types/atomic-element-reject.fab",
    "gpu-core-types/atomic-operations.fab",
    "gpu-core-types/f16-bf16-reject.fab",
    "gpu-core-types/matrix-register.fab",
    "gpu-core-types/matrix-tensor-reject.fab",
    "iace/functio-fallibilis.fab",
    "iace/functio-propagans.fab",
    "iace/iace-si-guard.fab",
    "importa/default-braced.fab",
    "importa/default-minimal.fab",
    "importa/importa.fab",
    "in/in.fab",
    "incipiet/incipiet.fab",
    "instans/instans.fab",
    "integratio/arena-mixta.fab",
    "integratio/discerne-insanum.fab",
    "integratio/fluxus-cede.fab",
    "intervallum/algebra.fab",
    "intervallum/conversio.fab",
    "intra/intra.fab",
    "intrinseca/copia-algebra.fab",
    "intrinseca/copia-fundamenta.fab",
    "intrinseca/fractus-approximata.fab",
    "intrinseca/fractus-comparatio.fab",
    "intrinseca/fractus-rotundatio.fab",
    "intrinseca/numeric-operator-methods.fab",
    "intrinseca/numerus-methodi.fab",
    "intrinseca/primitiva.fab",
    "intrinseca/textus-quaestiones.fab",
    "intrinseca/textus-transformationes.fab",
    "intrinseca/vacua-ascribere.fab",
    "itera/cursor-iteratio.fab",
    "itera/de.fab",
    "json/json.fab",
    "literalia/block-string.fab",
    "literalia/forma.fab",
    "membrum/membrum.fab",
    "meta/versio.fab",
    "nihil/nihil.fab",
    "numquam/numquam.fab",
    "octeti/octeti.fab",
    "octeti/unify.fab",
    "operandus/operandus.fab",
    "operatores/function-types.fab",
    "operatores/nonnull-chain.fab",
    "operatores/numerus-overflow.fab",
    "optio/optio.fab",
    "optiones/optiones.fab",
    "prae/prae.fab",
    "praefixum/praefixum.fab",
    "reddet/reddet.fab",
    "rumpe/rumpe-top-level-error.fab",
    "sparsa/access.fab",
    "sparsa/conversio-reject.fab",
    "sparsa/conversio.fab",
    "sparsa/decl.fab",
    "sparsa/non-numeric-reject.fab",
    "sparsa/sparsa-codegen-smoke.fab",
    "sparsa/sugar.fab",
    "tabula/tabula.fab",
    "tacebit/tacebit.fab",
    "tensor/arithmetic-elementwise.fab",
    "tensor/arithmetic-matmul.fab",
    "tensor/arithmetic-reduction.fab",
    "tensor/arithmetic-reject.fab",
    "tensor/bracket-access.fab",
    "tensor/decl.fab",
    "tensor/index-width.fab",
    "tensor/method-errors.fab",
    "tensor/method-policy.fab",
    "tensor/placement-execution-v1.fab",
    "tensor/shape.fab",
    "tensor/textus.fab",
    "type-hole-union/type-hole-union.fab",
    "typi/sized-family-error.fab",
    "typus/typus.fab",
    "ubique/ubique.fab",
    "unio/unio.fab",
    "variandum/variandum.fab",
    "vector/builtins.fab",
    "vector/cross.fab",
    "vector/decl.fab",
    "vector/dot.fab",
    "vector/elementwise.fab",
    "vector/infer.fab",
    "vector/sugar.fab",
    "vector/swizzle.fab",
    "vocatio/vocatio.fab",
];

/// Exempla expected to fail with a specific Faber compile-error message.
pub(crate) const SWIFT_EXPECTED_COMPILE_FAILURES: &[(&str, &str)] = &[
    // JSON types are not supported for Swift.
    // Protected/test fixtures with compiler-level gates.
    ("protecta/protecta.fab", "protecta_reserved"),
];

/// Baseline floor for accepted outcomes (passes + expected failures).
// S7-U6 ratchet (2026-08-09): the Stage 7 combined ledger pass shrank
// SWIFT_EXPECTED_FAILURES to 144; the lane measures 164 runnable passes and
// 309 accepted outcomes (swiftc 6.3.3, exempla swift e2e). Floors raised to
// the measured values (≤ measured runs).
pub(crate) const EXPECTED_SWIFT_PASS_FLOOR: usize = 164;
pub(crate) const EXPECTED_SWIFT_ACCEPTED_OUTCOME_FLOOR: usize = 309;
pub(crate) const EXPECTED_SWIFT_EXPECTED_FAILURE_CEILING: usize = 244;
