use std::path::{Path, PathBuf};

use radix::codegen::Target;
use radix::diagnostics::Diagnostic;

use super::{BuildLayout, FaberManifest};

/// Generate a minimal, deterministic `Cargo.toml` for the emitted Rust crate.
///
/// The Rust edition is fixed at 2021 for backend output; Faber source edition
/// is manifest metadata for the language frontend and does not imply a Rust
/// edition. `binary_name` must already be sanitized for Cargo.
fn generate_cargo_toml(meta: &FaberManifest, binary_name: &str, rust_code: &str) -> String {
    let version = if meta.package.version.trim().is_empty() {
        "0.1.0"
    } else {
        meta.package.version.trim()
    };
    render_generated_cargo_toml(binary_name, version, rust_code)
}

fn render_generated_cargo_toml(name: &str, version: &str, rust_code: &str) -> String {
    let faber_path = faber_runtime_path();
    let mut deps = format!(
        "faber = {{ package = \"faber-runtime\", path = \"{}\" }}\n",
        faber_path.display(),
    );
    if generated_code_needs_tokio(rust_code) {
        deps.push_str("tokio = { version = \"1\", features = [\"rt\", \"net\", \"time\"] }\n");
    }

    format!(
        r#"[package]
name = "{name}"
version = "{version}"
edition = "2021"

# This crate was generated by `faber build` from the package's faber.toml.
# Source of truth: faber.toml at the package root.
# Do not edit this file by hand.

[workspace]
# Empty workspace table keeps this generated crate independent when the
# package lives inside the faber repository workspace tree (e.g. examples/).
# Prevents "current package believes it's in a workspace" errors for
# `cargo build/test --manifest-path target/faber/Cargo.toml`.

[dependencies]
{deps}"#,
        name = name,
        version = version,
        deps = deps
    )
}

fn generated_code_needs_tokio(rust_code: &str) -> bool {
    rust_code.contains("tokio::") || rust_code.contains("__faber_block_on")
}

fn faber_runtime_path() -> PathBuf {
    // Public `faber` repo lives beside private `radix` under faberlang/.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../radix/crates/faber-runtime")
}

/// Write the generated Rust crate tree under the layout's `target/faber/` directory.
///
/// The generated crate owns exactly `target/faber/Cargo.toml` and
/// `target/faber/src/main.rs`. Other files under `target/` are Cargo artifacts
/// or user-adjacent build output and are intentionally left alone.
pub fn emit_generated_crate(
    layout: &BuildLayout,
    rust_code: &str,
    meta: Option<&FaberManifest>,
) -> Result<PathBuf, Box<Diagnostic>> {
    use std::fs;

    let src_dir = layout.generated_crate_root.join("src");
    if let Err(err) = fs::create_dir_all(&src_dir) {
        return Err(Box::new(Diagnostic::io_error(&src_dir, err)));
    }

    let cargo_src = if let Some(m) = meta {
        generate_cargo_toml(m, layout.binary_name(), rust_code)
    } else {
        render_generated_cargo_toml(layout.binary_name(), "0.1.0", rust_code)
    };
    if let Err(err) = fs::write(&layout.generated_cargo_manifest, &cargo_src) {
        return Err(Box::new(Diagnostic::io_error(
            &layout.generated_cargo_manifest,
            err,
        )));
    }

    // Policy: keep an outer generated marker even when backend codegen already
    // writes its own header, because this file belongs to the package builder's
    // generated crate contract.
    let final_code = format!(
        "// Generated by faber build — do not edit by hand.\n\
         // Crate layout: target/faber/  (see plan.md)\n\
         // Run with: cargo build --manifest-path target/faber/Cargo.toml --target-dir target\n\n{}",
        rust_code
    );
    let final_code = format_package_rust_source(&final_code);
    if let Err(err) = fs::write(&layout.generated_rust_entry, final_code) {
        return Err(Box::new(Diagnostic::io_error(
            &layout.generated_rust_entry,
            err,
        )));
    }

    Ok(layout.generated_crate_root.clone())
}

fn format_package_rust_source(source: &str) -> String {
    radix::tool::format_generated_code(Target::Rust, source).unwrap_or_else(|_| source.to_owned())
}

/// Invoke Cargo to build the generated crate and return the expected binary path.
///
/// Uses the layout's paths so that artifacts land in `<pkg>/target/debug/<name>`
/// (sibling to `target/faber/`, never nested).
///
/// Cargo's stdout/stderr are inherited to preserve native compiler progress and
/// diagnostics.
#[allow(dead_code)]
pub(crate) fn invoke_cargo_build(
    layout: &BuildLayout,
    release: bool,
) -> Result<PathBuf, Box<Diagnostic>> {
    use std::process::Command;

    let mut cmd = Command::new("cargo");
    cmd.arg("build")
        .arg("--manifest-path")
        .arg(&layout.generated_cargo_manifest)
        .arg("--target-dir")
        .arg(&layout.cargo_target_dir);

    if release {
        cmd.arg("--release");
    }

    let status = cmd.status().map_err(|e| {
        Box::new(Diagnostic::error(format!(
            "failed to spawn cargo (ensure cargo is installed and on PATH): {e}"
        )))
    })?;

    if !status.success() {
        return Err(Box::new(Diagnostic::error(format!(
            "cargo build exited with status {status}"
        ))));
    }

    let bin = if release {
        &layout.release_binary
    } else {
        &layout.debug_binary
    };
    Ok(bin.clone())
}

/// Invoke `cargo test` against the generated Rust crate.
///
/// Uses the package build directory contract:
///   --manifest-path <pkg>/target/faber/Cargo.toml
///   --target-dir <pkg>/target
///
/// The optional `filter` is passed before `--` as Cargo's Rust test name
/// filter. `harness_args` are forwarded after `--`. Test failures are not
/// converted into diagnostics; the harness exit status is returned verbatim so
/// the CLI can preserve Cargo's semantics.
#[allow(dead_code)]
pub fn invoke_cargo_test(
    layout: &BuildLayout,
    filter: Option<&str>,
    harness_args: &[String],
) -> Result<std::process::ExitStatus, Box<Diagnostic>> {
    use std::process::Command;

    let mut cmd = Command::new("cargo");
    cmd.arg("test")
        .arg("--manifest-path")
        .arg(&layout.generated_cargo_manifest)
        .arg("--target-dir")
        .arg(&layout.cargo_target_dir);

    if let Some(f) = filter {
        cmd.arg(f);
    }

    if !harness_args.is_empty() {
        cmd.arg("--");
        for arg in harness_args {
            cmd.arg(arg);
        }
    }

    let status = cmd.status().map_err(|e| {
        Box::new(Diagnostic::error(format!(
            "failed to spawn cargo (ensure cargo is installed and on PATH): {e}"
        )))
    })?;

    Ok(status)
}
