//! Tests for the reusable package-to-LLVM graph builder (S8.3).

use super::*;
use crate::package::test_support::{test_temp_dir, TestDir};
use radix::codegen::Target;
use std::fs;

const EXTERNAL_GREETING: &str = "__faber_external_product_geminus_module_adiutor_func_greeting";

const FIXTURE_ENTRY: &str = r#"# geminus — local-import consumer of adiutor.fab
importa ex "./adiutor" privata adiutor

incipit {
    nota adiutor.greeting("Tullia")
}
"#;

const FIXTURE_SIBLING: &str = r#"# adiutor — sibling module for geminus
functio greeting(textus nomen) → textus {
    redde "Salve, §!"(nomen)
}

incipit {
    nota greeting("adiutor")
}
"#;

/// Write the second local-import fixture (geminus: entry imports sibling
/// adiutor) under a temp dir and return the entry path. The fixture directory
/// name is fixed so the product identity (`geminus`) is deterministic.
fn write_geminus_fixture(dir: &TestDir) -> PathBuf {
    let package_dir = dir.join("geminus");
    fs::create_dir_all(&package_dir).expect("create geminus fixture dir");
    fs::write(package_dir.join("adiutor.fab"), FIXTURE_SIBLING).expect("write adiutor.fab");
    fs::write(package_dir.join("geminus.fab"), FIXTURE_ENTRY).expect("write geminus.fab");
    fs::write(package_dir.join("geminus.expected"), "Salve, Tullia!\n").expect("write expected");
    package_dir.join("geminus.fab")
}

fn llvm_config() -> radix::Config {
    radix::Config::default().with_target(Target::LlvmText)
}

fn build_fixture(dir: &TestDir, runtime_archive: Option<PathBuf>) -> (PathBuf, PackageLlvmBuild) {
    let entry = write_geminus_fixture(dir);
    let options = PackageLlvmOptions::new(dir.join("out"))
        .with_runtime_archive(runtime_archive)
        .with_native_flags(vec!["-lm".to_owned()]);
    let build = build_package_llvm(&llvm_config(), &entry, &options)
        .expect("package-to-LLVM build must succeed");
    (entry, build)
}

#[test]
fn package_llvm_builder_emits_one_module_per_unit_with_entry_symbol() {
    let dir = test_temp_dir("llvm-builder");
    let (entry, build) = build_fixture(&dir, None);

    assert_eq!(build.product, "geminus");
    assert_eq!(build.entry_unit, entry);

    // Two units — the entry consumer and the imported sibling — one .ll each.
    assert_eq!(build.modules.len(), 2, "expected two package units");
    let sibling = build
        .modules
        .iter()
        .find(|module| module.module_segments == ["adiutor".to_owned()])
        .expect("sibling unit must be present");
    let entry_module = build
        .modules
        .iter()
        .find(|module| module.is_entry)
        .expect("entry unit must be present");
    assert!(
        sibling.unit_path.ends_with("adiutor.fab"),
        "sibling module must carry its source unit path, got {}",
        sibling.unit_path.display()
    );
    assert!(
        entry_module.unit_path.ends_with("geminus.fab"),
        "entry module must carry its source unit path, got {}",
        entry_module.unit_path.display()
    );
    assert!(sibling.llvm_path.is_file(), "sibling .ll must be written");
    assert!(
        entry_module.llvm_path.is_file(),
        "entry .ll must be written"
    );

    // Exactly one module defines the host program entry (D11).
    let entry_text = fs::read_to_string(&entry_module.llvm_path).expect("read entry .ll");
    let sibling_text = fs::read_to_string(&sibling.llvm_path).expect("read sibling .ll");
    assert!(
        entry_text.contains("define %FaberRtExitV1 @__faber_program_entry_v1"),
        "entry module must define the program entry:\n{entry_text}"
    );
    assert!(
        !sibling_text.contains("__faber_program_entry_v1"),
        "library module must not emit a program entry:\n{sibling_text}"
    );

    // Cross-unit call parity: the entry declares/calls the sibling's external
    // symbol; the sibling module defines the SAME canonical symbol (D11 / D-PA2).
    assert!(
        entry_text.contains(EXTERNAL_GREETING),
        "entry module must declare/call the sibling external symbol:\n{entry_text}"
    );
    assert!(
        sibling_text.lines().any(|line| {
            line.trim_start().starts_with("define ")
                && line.contains(&format!("@{EXTERNAL_GREETING}"))
        }),
        "sibling module must define the external symbol:\n{sibling_text}"
    );

    // No .ll text concatenation: each module is an independent textual module
    // (own header), never a concatenation of both units.
    assert_eq!(
        entry_text
            .lines()
            .filter(|line| line.starts_with("; Generated by radix MIR LLVM IR probe"))
            .count(),
        1,
        "entry module must be a single textual module:\n{entry_text}"
    );
    assert_eq!(
        sibling_text
            .lines()
            .filter(|line| line.starts_with("; Generated by radix MIR LLVM IR probe"))
            .count(),
        1,
        "sibling module must be a single textual module:\n{sibling_text}"
    );
}

#[test]
fn package_llvm_builder_emits_one_norma_module_per_selected_unit() {
    const EXTERNAL_RETORTA: &str = "__faber_external_product_norma_module_chorda_func_retorta";
    const ENTRY: &str = r#"# chorda-consumer — imports a flat Norma unit
importa ex "norma:chorda" privata chorda

incipit {
    nota chorda.retorta("radar")
}
"#;

    let dir = test_temp_dir("llvm-builder");
    let package_dir = dir.join("chorda-consumer");
    fs::create_dir_all(&package_dir).expect("create chorda-consumer dir");
    fs::write(package_dir.join("chorda-consumer.fab"), ENTRY).expect("write entry");
    let entry = package_dir.join("chorda-consumer.fab");
    let options = PackageLlvmOptions::new(dir.join("out"));
    let build = build_package_llvm(&llvm_config(), &entry, &options)
        .expect("chorda-consumer package LLVM build must succeed");

    // S8.5 Norma graph: entry + ONE selected flat Norma unit (transitive used
    // modules only), one .ll per unit.
    assert_eq!(
        build.modules.len(),
        2,
        "expected the entry unit plus one selected Norma unit"
    );
    let entry_module = build
        .modules
        .iter()
        .find(|module| module.is_entry)
        .expect("entry module");
    let norma_module = build
        .modules
        .iter()
        .find(|module| module.is_norma)
        .expect("selected Norma unit module");
    assert_eq!(
        norma_module.module_segments,
        vec!["chorda".to_owned()],
        "Norma unit must carry its canonical module path"
    );
    assert!(
        norma_module.unit_path.ends_with("chorda.fab"),
        "Norma unit must point at its resolved interface source, got {}",
        norma_module.unit_path.display()
    );
    assert_eq!(
        norma_module.llvm_path.file_name().map(|name| name.to_string_lossy().into_owned()),
        Some("001-chorda-consumer-norma-chorda.ll".to_owned()),
        "Norma module file name must be deterministic and norma-prefixed"
    );
    let entry_text = fs::read_to_string(&entry_module.llvm_path).expect("read entry module");
    let norma_text = fs::read_to_string(&norma_module.llvm_path).expect("read Norma module");
    assert!(
        entry_text.contains(EXTERNAL_RETORTA),
        "entry module must declare/call the Norma external symbol:\n{entry_text}"
    );
    assert!(
        norma_text.lines().any(|line| {
            line.trim_start().starts_with("define ")
                && line.contains(&format!("@{EXTERNAL_RETORTA}"))
        }),
        "Norma module must define the external symbol:\n{norma_text}"
    );
    assert!(
        !norma_text.contains("__faber_program_entry_v1"),
        "Norma library module must not emit a program entry:\n{norma_text}"
    );
    assert_eq!(
        build.manifest.modules,
        build.modules.iter().map(|module| module.llvm_path.clone()).collect::<Vec<_>>(),
        "manifest must list one module per unit including the selected Norma unit"
    );
}

#[test]
fn package_llvm_builder_manifest_is_inspectable() {
    let dir = test_temp_dir("llvm-builder");
    let runtime_archive = dir.join("libfaber_host_llvm.a");
    let (_, build) = build_fixture(&dir, Some(runtime_archive.clone()));

    let manifest = &build.manifest;
    assert_eq!(
        manifest.modules,
        build
            .modules
            .iter()
            .map(|module| module.llvm_path.clone())
            .collect::<Vec<_>>(),
        "manifest module list must be the exact deterministic module list"
    );
    assert_eq!(
        manifest.entry_module,
        build
            .modules
            .iter()
            .find(|module| module.is_entry)
            .map(|module| module.llvm_path.clone())
            .expect("entry module in manifest"),
        "manifest must record the exactly-one entry module"
    );
    assert_eq!(manifest.runtime_archive, Some(runtime_archive));
    assert_eq!(manifest.native_flags, vec!["-lm".to_owned()]);
    assert!(manifest.output.ends_with("geminus"), "linker output path");
    assert!(
        manifest
            .binary_path
            .ends_with("target/faber/llvm/bin/geminus"),
        "binary path must be the canonical Faber target layout, got {}",
        manifest.binary_path.display()
    );
}

#[test]
fn package_llvm_builder_is_deterministic() {
    let dir = test_temp_dir("llvm-builder");
    let entry = write_geminus_fixture(&dir);
    let options = PackageLlvmOptions::new(dir.join("out-a"));
    let first =
        build_package_llvm(&llvm_config(), &entry, &options).expect("first build must succeed");
    let options = PackageLlvmOptions::new(dir.join("out-b"));
    let second =
        build_package_llvm(&llvm_config(), &entry, &options).expect("second build must succeed");

    assert_eq!(
        first
            .manifest
            .modules
            .iter()
            .map(|path| path.file_name().expect("module file name"))
            .collect::<Vec<_>>(),
        second
            .manifest
            .modules
            .iter()
            .map(|path| path.file_name().expect("module file name"))
            .collect::<Vec<_>>(),
        "module order and file names must be deterministic across builds"
    );
    for (left, right) in first.modules.iter().zip(second.modules.iter()) {
        let left_text = fs::read_to_string(&left.llvm_path).expect("read first .ll");
        let right_text = fs::read_to_string(&right.llvm_path).expect("read second .ll");
        assert_eq!(
            left_text,
            right_text,
            "module text must be identical across builds: {}",
            left.llvm_path.display()
        );
    }
}

#[test]
fn package_llvm_builder_single_unit_package() {
    let dir = test_temp_dir("llvm-builder");
    let package_dir = dir.join("solum");
    fs::create_dir_all(&package_dir).expect("create solum dir");
    fs::write(
        package_dir.join("solum.fab"),
        "incipit {\n    nota \"solus\"\n}\n",
    )
    .expect("write solum.fab");
    let entry = package_dir.join("solum.fab");
    let options = PackageLlvmOptions::new(dir.join("out"));
    let build = build_package_llvm(&llvm_config(), &entry, &options)
        .expect("single-unit package build must succeed");

    assert_eq!(build.modules.len(), 1);
    assert!(build.modules[0].is_entry);
    assert_eq!(
        build.manifest.modules,
        vec![build.modules[0].llvm_path.clone()]
    );
    assert_eq!(build.manifest.entry_module, build.modules[0].llvm_path);
}
