//! Subprocess checks for `faber emit`.

use std::fs;
use std::io::{Read, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};

fn run_faber_emit_faber_stdin(source: &str) -> String {
    let mut child = Command::new(env!("CARGO_BIN_EXE_faber"))
        .args(["emit", "-t", "faber", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn faber emit");

    child
        .stdin
        .take()
        .expect("stdin")
        .write_all(source.as_bytes())
        .expect("write source");

    let mut stdout = String::new();
    child
        .stdout
        .take()
        .expect("stdout")
        .read_to_string(&mut stdout)
        .expect("read stdout");

    let mut stderr = String::new();
    if let Some(mut err) = child.stderr.take() {
        let _ = err.read_to_string(&mut stderr);
    }
    let status = child.wait().expect("wait");
    assert!(status.success(), "faber emit -t faber failed: {stderr}");
    stdout
}

fn corpus_root() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../examples/corpus")
}

fn reader_locale_example_root(locale: &str) -> PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../examples/reader-locale")
        .join(locale)
}

fn temp_dir(label: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("faber-emit-integration-{label}-{nanos}"));
    fs::create_dir_all(&dir).expect("create temp dir");
    dir
}

fn write_plain_file(label: &str, contents: &str) -> PathBuf {
    let dir = temp_dir(label);
    let path = dir.join("plain.txt");
    fs::write(&path, contents).expect("write plain file");
    path
}

fn run_faber(args: &[&str]) -> (String, String, bool) {
    let mut child = Command::new(env!("CARGO_BIN_EXE_faber"))
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn faber emit");

    let mut stdout = String::new();
    child
        .stdout
        .take()
        .expect("stdout")
        .read_to_string(&mut stdout)
        .expect("read stdout");

    let mut stderr = String::new();
    if let Some(mut err) = child.stderr.take() {
        let _ = err.read_to_string(&mut stderr);
    }
    let status = child.wait().expect("wait");
    (stdout, stderr, status.success())
}

fn run_faber_emit(args: &[&str]) -> (String, String, bool) {
    run_faber(args)
}

fn write_basic_package(label: &str, source: &str) -> PathBuf {
    let package = temp_dir(label);
    fs::create_dir_all(package.join("src")).expect("create src");
    fs::write(
        package.join("faber.toml"),
        r#"
[package]
name = "cli-test"

[paths]
source = "src"
entry = "main.fab"
"#,
    )
    .expect("write manifest");
    fs::write(package.join("src/main.fab"), source).expect("write entry");
    package
}

#[test]
fn emit_wgsl_text_on_single_fab_file_succeeds() {
    let kernel = corpus_root().join("vector/kernel.fab");
    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "-t",
        "wgsl-text",
        kernel.to_str().expect("kernel path"),
    ]);
    assert!(ok, "faber emit -t wgsl-text failed: {stderr}");
    assert!(
        stdout.contains("fn vec_scale"),
        "expected WGSL entry function in output:\n{stdout}"
    );
}

#[test]
fn emit_llvm_text_on_single_fab_file_succeeds() {
    let source = corpus_root().join("incipit/salve-munde.fab");
    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "-t",
        "llvm-text",
        source.to_str().expect("source path"),
    ]);
    assert!(ok, "faber emit -t llvm-text failed: {stderr}");
    assert!(
        stdout.contains("define"),
        "expected LLVM IR in output:\n{stdout}"
    );
}

#[test]
fn emit_reflection_prints_wgsl_sidecar_json() {
    let kernel = corpus_root().join("vector/kernel.fab");
    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--reflection",
        "-t",
        "wgsl-text",
        kernel.to_str().expect("kernel path"),
    ]);
    assert!(ok, "faber emit --reflection failed: {stderr}");
    assert!(
        stdout.contains(r#""target": "wgsl-text""#),
        "expected GPU reflection JSON:\n{stdout}"
    );
    assert!(stdout.contains(r#""entry_name": "vec_scale""#), "{stdout}");
}

#[test]
fn emit_faber_target_routes_to_canonical_faber_output() {
    let output = run_faber_emit_faber_stdin("incipit {\n  nota \"ok\"\n}\n");

    assert!(
        output.contains("incipit {"),
        "expected Faber output:\n{output}"
    );
    assert!(
        !output.contains("// Generated by radix"),
        "Faber emit must not fall through to Rust output:\n{output}"
    );
}

#[test]
fn package_emit_honors_output_path() {
    let package = write_basic_package(
        "package-emit-output",
        r#"
incipit {
    nota "package emit"
}
"#,
    );
    let output = package.join("out/generated.rs");

    let (stdout, stderr, ok) = run_faber(&[
        "emit",
        "-t",
        "rust",
        "-o",
        output.to_str().expect("output path"),
        package.to_str().expect("package path"),
    ]);

    assert!(ok, "faber package emit failed: {stderr}");
    assert!(
        stdout.is_empty(),
        "emit -o should not write generated code to stdout: {stdout}"
    );
    let emitted = fs::read_to_string(&output).expect("read emitted rust");
    assert!(
        emitted.contains("fn main()"),
        "expected Rust main:\n{emitted}"
    );
    assert!(
        emitted.contains("package emit"),
        "expected package source in output:\n{emitted}"
    );
}

#[test]
fn package_check_diagnostics_uses_expanded_renderer() {
    let package = write_basic_package(
        "package-check-diagnostics",
        r#"
incipit {
    fixum numerus n ← "not a number"
    nota n
}
"#,
    );

    let (normal_stdout, normal_stderr, normal_ok) =
        run_faber(&["check", package.to_str().expect("package path")]);
    assert!(!normal_ok, "invalid package check should fail");
    assert!(normal_stdout.is_empty());
    // ALLOW_DIAGNOSTIC_RENDER_TEXT: CLI rendered diagnostic contract
    assert!(
        normal_stderr.contains("error[SEM010:"),
        "normal diagnostics should use coded compact headers:\n{normal_stderr}"
    );
    assert!(
        !normal_stderr.contains("\nphase:"),
        "normal package check must not render expanded records:\n{normal_stderr}"
    );

    let (expanded_stdout, expanded_stderr, expanded_ok) = run_faber(&[
        "check",
        "--diagnostics",
        package.to_str().expect("package path"),
    ]);
    assert!(
        !expanded_ok,
        "invalid package check --diagnostics should fail"
    );
    assert!(expanded_stdout.is_empty());
    // ALLOW_DIAGNOSTIC_RENDER_TEXT: CLI rendered diagnostic contract
    assert!(
        expanded_stderr.contains("error[")
            && expanded_stderr.contains("\nphase:")
            && expanded_stderr.contains("\nspan:"),
        "expanded diagnostics should include phase and span records:\n{expanded_stderr}"
    );
}

#[test]
fn check_reader_locale_accepts_direct_entry_file_input() {
    let example = reader_locale_example_root("th-TH");
    let entry = example.join("src/main.fab");

    let (stdout, stderr, ok) = run_faber(&[
        "check",
        "--reader-locale",
        "th-TH",
        entry.to_str().expect("entry path"),
    ]);

    assert!(ok, "reader-locale entry-file check failed:\n{stderr}");
    assert!(stdout.is_empty(), "check should not write stdout: {stdout}");
    assert!(
        stderr.contains("ok:"),
        "expected check success marker on stderr:\n{stderr}"
    );
}

#[test]
fn check_reader_locale_accepts_manifest_file_input() {
    let example = reader_locale_example_root("th-TH");
    let manifest = example.join("faber.toml");

    let (stdout, stderr, ok) = run_faber(&[
        "check",
        "--reader-locale",
        "th-TH",
        manifest.to_str().expect("manifest path"),
    ]);

    assert!(ok, "reader-locale manifest check failed:\n{stderr}");
    assert!(stdout.is_empty(), "check should not write stdout: {stdout}");
    assert!(
        stderr.contains("ok:"),
        "expected check success marker on stderr:\n{stderr}"
    );
}

#[test]
fn emit_reader_locale_accepts_direct_entry_file_input() {
    let example = reader_locale_example_root("th-TH");
    let entry = example.join("src/main.fab");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--reader-locale",
        "th-TH",
        entry.to_str().expect("entry path"),
    ]);

    assert!(ok, "reader-locale entry-file emit failed:\n{stderr}");
    assert!(
        stdout.contains("fn ทักทาย"),
        "expected localized Rust emit output:\n{stdout}"
    );
}

#[test]
fn emit_reader_locale_accepts_manifest_file_input() {
    let example = reader_locale_example_root("th-TH");
    let manifest = example.join("faber.toml");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--reader-locale",
        "th-TH",
        manifest.to_str().expect("manifest path"),
    ]);

    assert!(ok, "reader-locale manifest emit failed:\n{stderr}");
    assert!(
        stdout.contains("fn ทักทาย"),
        "expected localized Rust emit output:\n{stdout}"
    );
}

#[test]
fn emit_reader_locale_rejects_stdin_input() {
    let (stdout, stderr, ok) = run_faber_emit(&["emit", "--reader-locale", "th-TH", "-"]);

    assert!(!ok, "reader-locale stdin emit should fail");
    assert!(
        stdout.is_empty(),
        "rejected emit should not write stdout: {stdout}"
    );
    assert!(
        stderr.contains("--reader-locale th-TH requires a package path or .fab entry file"),
        "expected stdin shape rejection, got:\n{stderr}"
    );
}

#[test]
fn emit_reader_locale_rejects_forced_package_stdin_input() {
    let (stdout, stderr, ok) =
        run_faber_emit(&["emit", "--package", "--reader-locale", "th-TH", "-"]);

    assert!(!ok, "emit should reject stdin reader-locale package input");
    assert!(
        stdout.is_empty(),
        "rejected emit should not write stdout: {stdout}"
    );
    assert!(
        stderr.contains("--reader-locale th-TH requires a package path or .fab entry file"),
        "expected stdin shape rejection, got:\n{stderr}"
    );
}

#[test]
fn emit_reader_locale_rejects_existing_non_package_file() {
    let plain = write_plain_file("emit-reader-locale-plain-file", "temp");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--reader-locale",
        "th-TH",
        plain.to_str().expect("plain path"),
    ]);

    assert!(
        !ok,
        "emit should reject existing non-package files for reader-locale input"
    );
    assert!(
        stdout.is_empty(),
        "rejected emit should not write stdout: {stdout}"
    );
    assert!(
        stderr.contains("--reader-locale th-TH requires a package path or .fab entry file"),
        "expected reader-locale shape rejection, got:\n{stderr}"
    );
}

#[test]
fn emit_reader_locale_forced_package_rejects_existing_non_package_file() {
    let plain = write_plain_file("emit-reader-locale-force-package", "temp");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--package",
        "--reader-locale",
        "th-TH",
        plain.to_str().expect("plain path"),
    ]);

    assert!(
        !ok,
        "forced package reader-locale should reject existing non-package files"
    );
    assert!(
        stdout.is_empty(),
        "rejected emit should not write stdout: {stdout}"
    );
    assert!(
        stderr.contains("--reader-locale th-TH requires a package path or .fab entry file"),
        "expected reader-locale shape rejection, got:\n{stderr}"
    );
}

#[test]
fn emit_reader_locale_missing_package_path_surfaces_missing_path_error() {
    let (stdout, stderr, ok) =
        run_faber_emit(&["emit", "--reader-locale", "th-TH", "missing-package"]);

    assert!(!ok, "missing package path should fail");
    assert!(
        stdout.is_empty(),
        "missing package path should not write stdout: {stdout}"
    );
    assert!(
        !stderr.contains("--reader-locale th-TH requires a package path or .fab entry file"),
        "missing package path should reach the underlying filesystem error, got:\n{stderr}"
    );
    assert!(
        stderr.contains("cannot read 'missing-package': No such file or directory"),
        "expected missing path error, got:\n{stderr}"
    );
}

#[test]
fn emit_reader_locale_rejects_multiple_direct_inputs() {
    let example = reader_locale_example_root("th-TH");
    let entry_a = example.join("src/main.fab");
    let entry_b = example.join("src/lib.fab");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--reader-locale",
        "th-TH",
        entry_a.to_str().expect("entry path"),
        entry_b.to_str().expect("entry path"),
    ]);

    assert!(
        !ok,
        "emit should reject reader-locale when multiple direct inputs are supplied"
    );
    assert!(
        stdout.is_empty(),
        "rejected emit should not write stdout: {stdout}"
    );
    assert!(
        stderr.contains("--reader-locale th-TH requires a package path or .fab entry file"),
        "expected multiple-input reader-locale rejection, got:\n{stderr}"
    );
}

#[test]
fn emit_faber_target_localizes_reader_locale() {
    // Phase 2: `faber emit -t faber --reader-locale=<X>` emits localized Faber
    // (the old "deferred" rejection is gone). Thai source re-emits in the Thai
    // surface.
    let example = reader_locale_example_root("th-TH");
    let entry = example.join("src/main.fab");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "-t",
        "faber",
        "--reader-locale",
        "th-TH",
        entry.to_str().expect("entry path"),
    ]);

    assert!(ok, "faber emit should succeed with reader locale: {stderr}");
    assert!(
        stdout.contains("ฟังก์ชัน"),
        "localized emit should produce the Thai surface: {stdout}"
    );
    assert!(
        !stdout.contains("functio"),
        "localized emit should not emit the Latin keyword: {stdout}"
    );
}

#[test]
#[ignore = "pre-existing: Arabic reader-locale parse error at lines 152/197 of ~10-line source; unrelated to annotation/codegen fixes"]
fn emit_faber_reader_locale_arabic_preserves_logical_order() {
    // Phase 3 (req. #9): Arabic emit preserves logical (codepoint) order. The
    // emitted bytes decode to Arabic keyword codepoints in canonical logical
    // sequence; no Bidi isolates / embedding controls are inserted (logical
    // order is invariant; visual reordering would be a correctness bug).
    let example = reader_locale_example_root("ar");
    let entry = example.join("src/main.fab");

    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "-t",
        "faber",
        "--reader-locale",
        "ar",
        entry.to_str().expect("entry path"),
    ]);

    assert!(ok, "arabic emit should succeed: {stderr}");
    // functio -> دالة, incipit -> بداية, in logical order.
    assert!(
        stdout.contains("دالة"),
        "arabic emit should localize functio: {stdout}"
    );
    assert!(
        stdout.contains("بداية"),
        "arabic emit should localize incipit: {stdout}"
    );
    assert!(
        !stdout.contains("functio"),
        "arabic emit should not emit the Latin keyword: {stdout}"
    );
    // No Bidi / directional embedding controls. Logical order means scalar
    // values stream in source order; any directional control is a visual bug.
    const BIDI_CONTROLS: &[char] = &[
        '\u{202A}', '\u{202B}', '\u{202C}', '\u{202D}', '\u{202E}', // LRE/RLE/PDF/LRO/RLO
        '\u{2066}', '\u{2067}', '\u{2068}', '\u{2069}', // LRI/RLI/FSI/PDI
    ];
    assert!(
        !stdout.chars().any(|c| BIDI_CONTROLS.contains(&c)),
        "arabic emit must not inject Bidi controls (logical order invariant): {stdout}"
    );
}
