//! Subprocess checks for `faber emit`.

use std::fs;
use std::io::{Read, Write};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};

fn run_faber_emit_faber_stdin(source: &str) -> String {
    let mut child = Command::new(env!("CARGO_BIN_EXE_faber"))
        .args(["emit", "-t", "faber", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn faber emit");

    child
        .stdin
        .take()
        .expect("stdin")
        .write_all(source.as_bytes())
        .expect("write source");

    let mut stdout = String::new();
    child
        .stdout
        .take()
        .expect("stdout")
        .read_to_string(&mut stdout)
        .expect("read stdout");

    let mut stderr = String::new();
    if let Some(mut err) = child.stderr.take() {
        let _ = err.read_to_string(&mut stderr);
    }
    let status = child.wait().expect("wait");
    assert!(status.success(), "faber emit -t faber failed: {stderr}");
    stdout
}

fn workspace_root() -> std::path::PathBuf {
    // Sibling private radix tree (faberlang/radix).
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../radix")
}

fn temp_dir(label: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("faber-emit-integration-{label}-{nanos}"));
    fs::create_dir_all(&dir).expect("create temp dir");
    dir
}

fn run_faber(args: &[&str]) -> (String, String, bool) {
    let mut child = Command::new(env!("CARGO_BIN_EXE_faber"))
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn faber emit");

    let mut stdout = String::new();
    child
        .stdout
        .take()
        .expect("stdout")
        .read_to_string(&mut stdout)
        .expect("read stdout");

    let mut stderr = String::new();
    if let Some(mut err) = child.stderr.take() {
        let _ = err.read_to_string(&mut stderr);
    }
    let status = child.wait().expect("wait");
    (stdout, stderr, status.success())
}

fn run_faber_emit(args: &[&str]) -> (String, String, bool) {
    run_faber(args)
}

fn write_basic_package(label: &str, source: &str) -> PathBuf {
    let package = temp_dir(label);
    fs::create_dir_all(package.join("src")).expect("create src");
    fs::write(
        package.join("faber.toml"),
        r#"
[package]
name = "cli-test"

[paths]
source = "src"
entry = "main.fab"
"#,
    )
    .expect("write manifest");
    fs::write(package.join("src/main.fab"), source).expect("write entry");
    package
}

#[test]
fn emit_wgsl_text_on_single_fab_file_succeeds() {
    let kernel = workspace_root().join("crates/exempla/corpus/vector/kernel.fab");
    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "-t",
        "wgsl-text",
        kernel.to_str().expect("kernel path"),
    ]);
    assert!(ok, "faber emit -t wgsl-text failed: {stderr}");
    assert!(
        stdout.contains("fn vec_scale"),
        "expected WGSL entry function in output:\n{stdout}"
    );
}

#[test]
fn emit_llvm_text_on_single_fab_file_succeeds() {
    let source = workspace_root().join("crates/exempla/corpus/incipit/salve-munde.fab");
    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "-t",
        "llvm-text",
        source.to_str().expect("source path"),
    ]);
    assert!(ok, "faber emit -t llvm-text failed: {stderr}");
    assert!(
        stdout.contains("define"),
        "expected LLVM IR in output:\n{stdout}"
    );
}

#[test]
fn emit_reflection_prints_wgsl_sidecar_json() {
    let kernel = workspace_root().join("crates/exempla/corpus/vector/kernel.fab");
    let (stdout, stderr, ok) = run_faber_emit(&[
        "emit",
        "--reflection",
        "-t",
        "wgsl-text",
        kernel.to_str().expect("kernel path"),
    ]);
    assert!(ok, "faber emit --reflection failed: {stderr}");
    assert!(
        stdout.contains(r#""target": "wgsl-text""#),
        "expected GPU reflection JSON:\n{stdout}"
    );
    assert!(stdout.contains(r#""entry_name": "vec_scale""#), "{stdout}");
}

#[test]
fn emit_faber_target_routes_to_canonical_faber_output() {
    let output = run_faber_emit_faber_stdin("incipit {\n  nota \"ok\"\n}\n");

    assert!(
        output.contains("incipit {"),
        "expected Faber output:\n{output}"
    );
    assert!(
        !output.contains("// Generated by radix"),
        "Faber emit must not fall through to Rust output:\n{output}"
    );
}

#[test]
fn package_emit_honors_output_path() {
    let package = write_basic_package(
        "package-emit-output",
        r#"
incipit {
    nota "package emit"
}
"#,
    );
    let output = package.join("out/generated.rs");

    let (stdout, stderr, ok) = run_faber(&[
        "emit",
        "-t",
        "rust",
        "-o",
        output.to_str().expect("output path"),
        package.to_str().expect("package path"),
    ]);

    assert!(ok, "faber package emit failed: {stderr}");
    assert!(
        stdout.is_empty(),
        "emit -o should not write generated code to stdout: {stdout}"
    );
    let emitted = fs::read_to_string(&output).expect("read emitted rust");
    assert!(
        emitted.contains("fn main()"),
        "expected Rust main:\n{emitted}"
    );
    assert!(
        emitted.contains("package emit"),
        "expected package source in output:\n{emitted}"
    );
}

#[test]
fn package_check_diagnostics_uses_expanded_renderer() {
    let package = write_basic_package(
        "package-check-diagnostics",
        r#"
incipit {
    fixum numerus n ← "not a number"
    nota n
}
"#,
    );

    let (normal_stdout, normal_stderr, normal_ok) =
        run_faber(&["check", package.to_str().expect("package path")]);
    assert!(!normal_ok, "invalid package check should fail");
    assert!(normal_stdout.is_empty());
    // ALLOW_DIAGNOSTIC_RENDER_TEXT: CLI rendered diagnostic contract
    assert!(
        normal_stderr.contains("error[SEM010:"),
        "normal diagnostics should use coded compact headers:\n{normal_stderr}"
    );
    assert!(
        !normal_stderr.contains("\nphase:"),
        "normal package check must not render expanded records:\n{normal_stderr}"
    );

    let (expanded_stdout, expanded_stderr, expanded_ok) = run_faber(&[
        "check",
        "--diagnostics",
        package.to_str().expect("package path"),
    ]);
    assert!(
        !expanded_ok,
        "invalid package check --diagnostics should fail"
    );
    assert!(expanded_stdout.is_empty());
    // ALLOW_DIAGNOSTIC_RENDER_TEXT: CLI rendered diagnostic contract
    assert!(
        expanded_stderr.contains("error[")
            && expanded_stderr.contains("\nphase:")
            && expanded_stderr.contains("\nspan:"),
        "expanded diagnostics should include phase and span records:\n{expanded_stderr}"
    );
}
