//! Generated fmir-bin runner crate: write, render, and invoke.

use super::*;

pub(super) fn write_fmir_bin_runner(
    artifact_root: &Path,
    entrypoint_path: &Path,
    diagnostic_path: &Path,
    image: &[u8],
    release: bool,
) -> Result<(), Vec<Diagnostic>> {
    let runner_root = artifact_root.join(FMIR_BIN_RUNNER_CRATE_DIR);
    let runner_src = runner_root.join("src");
    fs::create_dir_all(&runner_src)
        .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])?;
    fs::write(
        runner_root.join("Cargo.toml"),
        render_fmir_bin_runner_cargo_toml(),
    )
    .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])?;
    fs::write(
        runner_src.join("main.rs"),
        render_fmir_bin_runner_main_rs(image),
    )
    .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])?;

    // Redirect the runner's cargo build to a shared target dir instead of
    // <pkg>/target/faber-mir/exe/runner-target/. This prevents ~1.4 GB of
    // compiled faber+radix artifacts from being written into every package
    // that runs `faber build --target fmir-bin`. The shared dir is reused
    // across all fmir-bin builds.
    let runner_target_dir = shared_fmir_bin_runner_target_dir();
    fs::create_dir_all(&runner_target_dir)
        .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])?;

    let built_runner = invoke_fmir_bin_runner_build(
        &runner_root.join("Cargo.toml"),
        &runner_target_dir,
        diagnostic_path,
        release,
    )?;
    fs::copy(&built_runner, entrypoint_path)
        .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])?;
    make_fmir_bin_entrypoint_executable(entrypoint_path, diagnostic_path)?;
    Ok(())
}

/// Shared target directory for fmir-bin runner cargo builds.
///
/// Uses `CARGO_TARGET_DIR` from the environment when set (respects `.cargo/config.toml`),
/// otherwise falls back to a per-user cache dir. This keeps the ~1.4 GB of
/// compiled faber+radix artifacts out of individual package directories.
pub(super) fn shared_fmir_bin_runner_target_dir() -> PathBuf {
    if let Some(dir) = std::env::var_os("CARGO_TARGET_DIR") {
        return PathBuf::from(dir).join("fmir-bin-runner");
    }
    std::env::var("HOME")
        .map(|h| PathBuf::from(h).join(".cache/faberlang-target/faber/fmir-bin-runner"))
        .unwrap_or_else(|_| std::env::temp_dir().join("faber-fmir-bin-runner-target"))
}

pub(super) fn render_fmir_bin_runner_cargo_toml() -> String {
    let faber_cli_path = toml_basic_string_path(Path::new(env!("CARGO_MANIFEST_DIR")));
    format!(
        r#"[package]
name = "{FMIR_BIN_RUNNER_PACKAGE_NAME}"
version = "0.0.0"
edition = "2021"

# This crate was generated by `faber build --target fmir-bin`.
# It is a fixed FMIR runner shell; the user program is embedded as image.fmir.
# Do not edit this file by hand.

[workspace]
# Keep the generated crate independent when a package lives in another
# workspace tree.

[dependencies]
faber = {{ path = "{faber_cli_path}", version = "={PACKAGE_MIR_TOOLCHAIN_VERSION}" }}
"#
    )
}

pub(super) fn render_fmir_bin_runner_main_rs(image: &[u8]) -> String {
    let mut source = format!("// embedded image {}\n", fnv64_hex(image));
    source.push_str(
        r#"fn main() {
    let args = std::env::args().skip(1).collect::<Vec<_>>();
    if let Err(diagnostics) = faber_cli::package::run_fmir_image_bytes_with_stdio(
        include_bytes!("../../image.fmir"),
        std::path::Path::new("embedded:image.fmir"),
        args,
    ) {
        for diagnostic in diagnostics {
            if diagnostic.is_error() {
                eprintln!("error: {}", diagnostic.message);
            } else {
                eprintln!("warning: {}", diagnostic.message);
            }
        }
        eprintln!("fmir image execution failed");
        std::process::exit(1);
    }
}
"#,
    );
    source
}

pub(super) fn invoke_fmir_bin_runner_build(
    manifest_path: &Path,
    target_dir: &Path,
    diagnostic_path: &Path,
    release: bool,
) -> Result<PathBuf, Vec<Diagnostic>> {
    let mut command = std::process::Command::new("cargo");
    command
        .arg("build")
        .arg("--manifest-path")
        .arg(manifest_path)
        .arg("--target-dir")
        .arg(target_dir);

    if release {
        command.arg("--release");
    }

    let status = command.status().map_err(|error| {
        vec![mir_diag(
            diagnostic_path,
            format!("failed to spawn cargo for fmir-bin runner: {error}"),
        )]
    })?;
    if !status.success() {
        return Err(vec![mir_diag(
            diagnostic_path,
            format!("fmir-bin runner cargo build exited with status {status}"),
        )]);
    }

    let profile = if release { "release" } else { "debug" };
    Ok(target_dir.join(profile).join(format!(
        "{FMIR_BIN_RUNNER_PACKAGE_NAME}{}",
        std::env::consts::EXE_SUFFIX
    )))
}

pub(super) fn toml_basic_string_path(path: &Path) -> String {
    escape_toml_basic_string(&path.to_string_lossy())
}

#[cfg(unix)]
pub(super) fn make_fmir_bin_entrypoint_executable(
    entrypoint_path: &Path,
    diagnostic_path: &Path,
) -> Result<(), Vec<Diagnostic>> {
    use std::os::unix::fs::PermissionsExt;

    let metadata = fs::metadata(entrypoint_path)
        .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])?;
    let mut permissions = metadata.permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(entrypoint_path, permissions)
        .map_err(|error| vec![mir_diag(diagnostic_path, error.to_string())])
}

#[cfg(not(unix))]
pub(super) fn make_fmir_bin_entrypoint_executable(
    _entrypoint_path: &Path,
    _diagnostic_path: &Path,
) -> Result<(), Vec<Diagnostic>> {
    Ok(())
}

/// FNV-1a provenance hash idiom shared by image and runner artifacts: a
/// fixed-width hex digest under an `fnv64:` prefix.
pub(super) fn fnv64_hex(bytes: &[u8]) -> String {
    format!("fnv64:{:016x}", fnv1a64(bytes))
}

pub(super) fn source_identity(
    path: &Path,
    package_root: &Path,
) -> Result<FmirTextSourceIdentity, Vec<Diagnostic>> {
    let bytes = fs::read(path).map_err(|error| {
        vec![mir_diag(
            path,
            format!("could not read fmir-text source identity: {error}"),
        )]
    })?;
    Ok(FmirTextSourceIdentity {
        file: relative_or_display(package_root, path),
        hash: fnv64_hex(&bytes),
    })
}

